language: clojure
lein: lein2
sudo: false
script:
  - lein test-all
  - lein with-profile +1.6 test-all
  - lein with-profile +1.7 test-all
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  include:
    - script: lein coverage
      jdk:    oraclejdk8
    - script: lein eastwood
      jdk:    oraclejdk8
