language: clojure
sudo: false
script:
  - lein test
  - lein with-profile +1.8 test
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk10
matrix:
  include:
    - script: lein coverage
      jdk:    oraclejdk8
    - script: lein eastwood
      jdk:    oraclejdk8
